### ISSUE TITLE
Missing values in mechanum robot and trajectory

### ISSUE THREAD

**Issue by jvedock** [TheConverseEngineer/FTC-BASE-CODE#14]
Several values are missing, im note sure if thereis a typo or if they were not imported or not defined or what but there are several missing values in those two files
MechanumRobot is missing "magnitude"
```java
normalize(wheelSpeeds, magnitude);
```

and trajectory is missing  "nextLine", and "currentStage"
```java
target = nextLine.absolute ? nextLine.B : nextLine.getFurthestPoint(intersectionsOnNextLine);
```

```java
int newStage = currentStage +  ((intersectionsOnNextLine.length > 0) ? 1 : 0);
```
(Note, "currentState" is a parameter in the method getRobotTarget, so this could be intended to go inside the method)

what are these values supposed to be

**Comment by TheConverseEngineer** [comment]
Is this issue resolved?

**Comment by jvedock** [comment]
one can only hope
