### ISSUE TITLE
institute full testing

### ISSUE THREAD

**Issue by jvedock** [TheConverseEngineer/FTC-BASE-CODE#19]
- [x] Point.java
- [ ] Graph.java
- [ ] PathLine.java
- [x] PathState.java
- [ ] Trajectory.java
- [ ] Waypoint.java
- [ ] Robot.java
- [ ] FTCBot.java
- [ ] MechanumBot.java

I'm going to need your help on some of these cause I don't really understand all of the math here well enough to write tests

**Comment by TheConverseEngineer** [comment]
Here are some test cases for geometry/Graph.java

Function 1: getClosestPoint(a, b, p) -> return the closest point to point P on line AB;
1. (2, 3); (5, 3); (4, 7) == (4, 3)
2. (-2, 3); (-5, 3); (-4, 7) == (-4, 3)
3. (-2, -3); (-5, -3); (-4, -7) == (-4, -3)
4. (5, 5); (5, -5); (-8, -1) == (5, -1)
5. (-3, 4); (5, -4); (-2, 3) == (-1, 2)
6. (-3, 4); (5, -4); (0, 1) == (-1, 2)


Feel free to check my math, it might not be accurate. Unfortunately, I can’t do the second function in my head, so I’ll do those when I get home.

Signing off, 
The Bloolean man

**Comment by jvedock** [comment]
*boolean

But thanks, ill implement those today

**Comment by jvedock** [comment]
Implemented but could you check your math on numbers 5 and 6, they fail

**Comment by jvedock** [comment]
this is not complete but it is no longer relavent so im closing it
