### ISSUE TITLE
Computer Vision Integration

### ISSUE THREAD

**Issue by TheConverseEngineer** [TheConverseEngineer/FTC-BASE-CODE#21]
The goal is to integrate computer vision as an object, and contain all setup and execution code in a neat orderly manner.

Goals:

- [ ] One line creation (single line constructor)
- [ ] Update method
- [ ] Get objects method

**Comment by jvedock** [comment]
Ill set up a basic file structure for the camera learning tomorrow, ill update here, but try not to add anything too much till then

**Comment by TheConverseEngineer** [comment]
Computer vision-related code will be placed in the new vision folder located in team code.

**Comment by jvedock** [comment]
found this and thought it might be helpful
[http://overchargedrobotics.org/wp-content/uploads/2018/08/Advanced-Programming-Vision.pdf](url)

**Comment by TheConverseEngineer** [comment]
I saw that, the implementation I tried is slightly different, but the same general idea. I’m done with the vuforia stuff, so I’m waiting for kickoff so that we can decide what pipelines to use.

**Comment by TheConverseEngineer** [comment]
This issue is being closed until kickoff
