### ISSUE TITLE
gamepad pull request

### ISSUE THREAD

**Issue by jvedock** [TheConverseEngineer/FTC-BASE-CODE#33]
This branch is for the gamepad plus pull request this adds increased functionality to the gamepad

Todo:
before merge:

- [x] get core working 
- [x] add sample class
- [x] test core

After Merge

- [ ] Make Learners guide specifically for this

**Comment by jvedock** [comment]
This is done but I don't have WiFi atm so I can't push

**Comment by TheConverseEngineer** [comment]
Do you want me to push?

**Comment by jvedock** [comment]
Update, this stays open until the null pointer exception is fixed

**Comment by jvedock** [comment]
I think i have fixed it, I will latest it at lunch but I can’t update it here because the WiFi is down >:(

**Comment by jvedock** [comment]
I did in fact fix it but i still can’t upload the code because WiFi

**Comment by jvedock** [comment]
Ill get this merged during lunch today now that it works
